#! ./bin/bash

SCRIPT_NAME=$(basename "$0")

echo "[$SCRIPT_NAME] Autogenerating settings. Make sure there is a running Timeplusd server at port 8463, and the Settings.h in the user_files. Also proton client at ~/Dev/bin "

# Autogenerate settings
~/Dev/bin/proton client -u admin --password changeme -q "
WITH
settings_from_cpp AS
(
    SELECT extract(line, 'M\\(\\w+, (\\w+),') AS name
    FROM file('Settings.h', LineAsString)
    WHERE match(line, '^\\s*M\\(')
),
main_content AS
(
    SELECT format('## {} {}\\n\\nType: {}\\n\\n{}\\n\\n',
                  name, '{#'||name||'}', lower(type), replace(replace(trim(BOTH '\\n' FROM description),'<','\<'),'{','\{')) as str
    FROM system.settings WHERE name IN settings_from_cpp
    ORDER BY name
),
'# Core Settings
<!-- Autogenerated -->
All below settings are also available in table \`system.settings\` and [the source code](https://github.com/timeplus-io/proton/blob/develop/src/Core/Settings.h). These settings are autogenerated for '||if(edition()='oss','proton','timeplusd')||' '||version()||' on '||to_string(today())||'.\n' AS prefix
SELECT prefix || (SELECT array_fold(acc,x->concat(acc,x),group_array(str),'') FROM main_content)
FORMAT LineAsString
" > 'docs/core-settings.md'

echo "[$SCRIPT_NAME] Autogenerating settings completed"
