/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  docSidebar: [
    {
      type: "category",
      label: "OVERVIEW",
      //collapsed: false,
      link: {
        type: "doc",
        id: "index",
      },
      items: [
        {
          type: "doc",
          id: "why-timeplus",
          label: "Why Timeplus",
        },
        {
          type: "doc",
          id: "architecture",
        },
        {
          type: "doc",
          id: "cluster",
        },
      ],
    },
    {
      type: "category",
      label: "GET STARTED",
      items: [
        {
          type: "doc",
          id: "quickstart",
        },
        {
          type: "category",
          label: "Guides & Tutorials",
          items: [
            // "understanding-watermark",
            "tutorial-sql-kafka",
            "tutorial-github",
            "marimo",
            "tutorial-sql-connect-kafka",
            "tutorial-sql-connect-ch",
            "tutorial-cdc-rpcn-pg-to-ch",
            {
              type: "category",
              label: "Streaming ETL",
              items: [
                "tutorial-sql-etl",
                "tutorial-sql-etl-kafka-to-ch",
                "tutorial-sql-etl-mysql-to-ch",
              ],
            },
            "tutorial-sql-join",
            "tutorial-python-udf",
            "sql-pattern-topn",
            "usecases",
            "tutorial-kv",
            "tutorial-sql-read-avro",
            "tutorial-testcontainers-java",
          ],
        },
        {
          type: "doc",
          id: "showcases",
        },
        {
          type: "doc",
          id: "howtos",
          label: "How Tos",
        },
      ]
    },
    {
      type: "category",
      label: "CONNECT DATA IN",
      link : {
        type: "doc",
        id: "connect-data-in",
      },
      items: [
        // {
        //   type: "category",
        //   label: "Native Client",
        //   link: {
        //     type: "doc",
        //     id: "native-client",
        //   },
        //   items: [
        //     {
        //       type: "doc",
        //       id: "idempotent",
        //     },
        //   ],
        // },
        {
          type: "category",
          label: "Apache Kafka",
          link: {
            type: "doc",
            id: "kafka-source",
          },
          items: ["kafka-schema-registry", "timeplus-format-schema"],
        },
        {
          type: "doc",
          label: "Apache Pulsar",
          id: "pulsar-source",
        },
        {
          type: "doc",
          label: "MySQL",
          id: "mysql-external-table",
        },
        {
          type: "doc",
          label: "Apache Iceberg",
          id: "iceberg-source",
        },
        {
          type: "doc",
          label: "MongoDB",
          id: "mongo-external-table",
        },
        {
          type: "doc",
          label: "PostgreSQL",
          id: "pg-external-table",
        },
        {
          type: "doc",
          label: "S3",
          id: "s3-source",
        },
        {
          type: "doc",
          label: "Log Stream",
          id: "log-stream",
        },
        {
          type: "doc",
          label: "Timeplus",
          id: "timeplus-source",
        },
        {
          type: "link",
          label: "Timeplus Random Stream",
          href: "https://docs.timeplus.com/sql-create-random-stream",
        },
      ]
    },
    {
      type: "category",
      label: "TRANSFORM DATA",
      link: {
        type: "doc",
        id: "transform-data",
      },
      items: [
        {
          type: "category",
          label: "Materialized View",
          link: {
            type: "doc",
            id: "materialized-view",
          },
          items: [
            {
              type: "doc",
              id: "materialized-view-lifecycle",
              label: "Lifecycle",
            },
            {
              type: "doc",
              id: "materialized-view-checkpoint",
              label: "Checkpoint",
            },
            {
              type: "doc",
              id: "materialized-view-high-availability",
              label: "High Availability",
            },
            {
              type: "doc",
              id: "materialized-perf-tuning",
              label: "Performance Tuning",
            },
            {
              type: "doc",
              id: "materialized-view-monitoring",
              label: "Monitoring",
            },
          ]
        },
        {
          type: "doc",
          id: "task",
          label: "Scheduled Task",
        },
        {
          type: "doc",
          id: "streaming-joins",
          label: "Streaming Joins"
        },
        {
          type: "category",
          label: "Streaming Aggregations",
          // link : {
          //   type: "doc",
          //   id: "streaming-aggregations",
          // },
          items : [
            {
              type: "doc",
              id: "global-aggregation",
              label: "Global",
            },
            {
              type: "doc",
              id: "tumble-aggregation",
              label: "Tumble",
            },
            {
              type: "doc",
              id: "hop-aggregation",
              label: "Hop",
            },
            {
              type: "doc",
              id: "session-aggregation",
              label: "Session",
            },
          ]
        },
        {
          type: "doc",
          id: "shuffle-data",
          label: "Shuffle Data"
        },
        {
          type: "doc",
          id: "jit",
          label: "Just-In-Time Compilation"
        },
        {
          type: "doc",
          id: "view",
          label: "View",
        },
      ]
    },
    {
      type: "category",
      label: "STORE & SERVE DATA",
      link: {
        type: "doc",
        id: "store-and-serve-data",
      },
      items: [
        {
          type: "category",
          label: "Streams",
          link: {
            type: "doc",
            id: "working-with-streams",
          },
          items: [
            {
              type: "category",
              label: "Append Stream",
              link: {
                type: "doc",
                id: "append-stream",
              },
              items: [
                {
                  type: "doc",
                  id: "append-stream-indexes",
                  label: "Indexes",
                },
                {
                  type: "doc",
                  id: "append-stream-codecs",
                  label: "Column Compression Codecs",
                },
                {
                  type: "doc",
                  id: "append-stream-ttl",
                  label: "TTL",
                },
                {
                  type: "doc",
                  id: "append-stream-tiered-storage",
                  label: "Tier Storage",
                },
              ]
            },
            {
              type: "doc",
              id: "versioned-stream",
            },
            {
              type: "doc",
              id: "changelog-stream",
            },
            {
              type: "category",
              label: "Mutable Stream",
              link: {
                type: "doc",
                id: "mutable-stream",
              },
              items: [
                {
                  type: "doc",
                  id: "mutable-stream-indexes",
                  label: "Indexes",
                },
                {
                  type: "doc",
                  id: "mutable-stream-versioned",
                  label: "Versioned Mutable Stream",
                },
                {
                  type: "doc",
                  id: "mutable-stream-coalesced",
                  label: "Coalesced Mutable Stream",
                },
                {
                  type: "doc",
                  id: "mutable-stream-ttl",
                  label: "TTL",
                },
              ]
            },
            {
              type: "doc",
              id: "rack-aware-placements",
              label: "Rack-aware Placements",
            },
          ],
        },
        {
          label: "Dictionary",
          type: "link",
          href: "https://docs.timeplus.com/sql-create-dictionary",
        },
        {
          type: "doc",
          id: "viz",
        },
      ]
    },
    {
      type: "category",
      label: "SEND DATA OUT",
      link: {
        type: "doc",
        id: "send-data-out",
      },
      items: [
        // {
        //   type: "doc",
        //   label: "Native Client",
        //   id: "native-client",
        // },
        {
          type: "doc",
          label: "Apache Kafka",
          id: "kafka-sink",
        },
        {
          type: "doc",
          label: "Apache Pulsar",
          id: "pulsar-sink",
        },
        {
          type: "doc",
          label: "Apache Iceberg",
          id: "iceberg-sink",
        },
        {
          type: "doc",
          label: "ClickHouse",
          id: "clickhouse-external-table",
        },
        {
          type: "doc",
          label: "S3",
          id: "s3-sink",
        },
        {
           type: "doc",
           label: "HTTP",
           id: "http-external-stream",
        },
        {
           type: "doc",
           label: "Datadog",
           id: "datadog-external",
        },
        {
           type: "doc",
           label: "Splunk",
           id: "splunk-external",
        },
        {
           type: "doc",
           label: "Elasticsearch",
           id: "elastic-external",
        },
        {
           type: "doc",
           label: "BigQuery",
           id: "bigquery-external",
        },
        {
           type: "doc",
           label: "Databricks",
           id: "databricks-external",
        },
        // {
        //   type: "doc",
        //   label: "MySQL",
        //   id: "mysql-external-table",
        // },
        // {
        //   type: "doc",
        //   label: "PostgreSQL",
        //   id: "pg-external-table",
        // },
        // {
        //   type: "doc",
        //   label: "MongoDB",
        //   id: "mongo-external-table",
        // },
        {
          type: "doc",
          label: "Timeplus",
          id: "timeplus-sink",
        },
        {
           type: "doc",
           label: "Slack",
           id: "slack-external",
        },
        {
          type: "doc",
          id: "alert",
        },
      ]
    },
    {
      type: "category",
      label: "SQL REFERENCE",
      items: [
        "query-syntax",
        "query-settings",
        "datatypes",
        {
          type: "category",
          label: "Statements",
          link: {
            type: "generated-index",
            title: "SQL Statements",
            description: "Overview of the SQL commands supported by Timeplus.",
            slug: "/category/commands",
            keywords: ["guides"],
          },
          items: [
            {
              label: "SELECT",
              type: "link",
              href: "https://docs.timeplus.com/query-syntax",
            },
            "sql-alter-stream",
            "sql-alter-view",
            {
              label: "CREATE ALERT",
              type: "link",
              href: "https://docs.timeplus.com/alert",
            },
            "sql-create-database",
            "sql-create-dictionary",
            "sql-create-disk",
            "sql-create-external-stream",
            "sql-create-external-table",
            "sql-create-format-schema",
            "sql-create-function",
            {
              label: "CREATE MATERIALIZED VIEW",
              type: "link",
              href: "https://docs.timeplus.com/materialized-view",
            },
            {
              label: "CREATE MUTABLE STREAM",
              type: "link",
              href: "https://docs.timeplus.com/mutable-stream",
            },
            "sql-create-random-stream",
            "sql-create-remote-function",
            {
              label: "CREATE STREAM",
              type: "link",
              href: "https://docs.timeplus.com/append-stream",
            },
            {
              label: "CREATE VIEW",
              type: "link",
              href: "https://docs.timeplus.com/view",
            },
            "sql-delete",
            "sql-drop-alert",
            "sql-drop-database",
            "sql-drop-dictionary",
            "sql-drop-external-table",
            "sql-drop-format-schema",
            "sql-drop-function",
            "sql-drop-stream",
            "sql-drop-view",
            "sql-explain",
            "sql-optimize",
            "sql-rename-stream",
            "sql-show-alerts",
            "sql-show-create",
            "sql-show-databases",
            "sql-show-dictionaries",
            "sql-show-disks",
            "sql-show-format-schemas",
            "sql-show-functions",
            "sql-show-streams",
            "sql-system-pause",
            "sql-system-recover",
            "sql-system-resume",
            "sql-system-set-log-level",
            "sql-system-transfer-leader",
            "sql-truncate-stream",
            "sql-use",
          ],
        },
        {
          type: "category",
          label: "Functions",
          collapsed: true,
          link: { type: "doc", id: "functions" },
          items: [
            {
              type: "category",
              label: "Regular Functions",
              link: {
                type: "generated-index",
                title: "Regular Functions",
                description: "Integrate Timeplus to your tool stacks.",
                slug: "/category/functions",
                keywords: ["guides"],
              },
              items: [
                "functions_for_type",
                "functions_for_comp",
                "functions_for_datetime",
                "functions_for_url",
                "functions_for_json",
                "functions_for_text",
                "functions_for_hash",
                "functions_for_random",
                "functions_for_logic",
                "functions_for_math",
                "functions_for_fin",
                "functions_for_geo",
                "functions_for_dict",
              ],
            },
            "functions_for_agg",
            "functions_for_streaming",
            "functions_for_table",
            {
              type: "category",
              label: "User Defined Functions",
              collapsed: false,
              link: {
                type: "doc",
                id: "udf",
              },
              items: [
                {
                  type: "doc",
                  id: "py-udf",
                },
                "js-udf",
                "sql-udf",
                "remote-udf",
              ],
            },
          ],
        },
        "grok",
      ],
    },
    {
      type: "category",
      label: "TIMEPLUS PROTON (OSS)",
      link: {
        type: "doc",
        id: "proton",
      },
      items: [
        {
          type: "doc",
          label: "Proton OSS vs Enterprise",
          id: "proton-oss-vs-enterprise",
        },
        "proton-faq",
      ],
    },
    {
      type: "category",
      label: "INTEGRATIONS",
      items: [
        {
          type: "category",
          label: "CLI, APIs & SDKs",
          items: [
            "proton-client",
            {
              type: "doc",
              id: "timeplusd-client",
            },
            {
              type: "category",
              label: "timeplus (CLI)",
              link: {
                type: "doc",
                id: "cli-reference",
              },
              items: [
                "cli-backup",
                "cli-diag",
                "cli-help",
                "cli-license",
                "cli-migrate",
                "cli-restart",
                "cli-restore",
                "cli-service",
                "cli-start",
                "cli-status",
                "cli-stop",
                "cli-sync",
                "cli-user",
                "cli-version",
              ],
            },
            "jdbc",
            {
              label: "ODBC Driver",
              type: "link",
              href: "https://github.com/timeplus-io/proton-odbc",
            },
            "timeplus-connect",
            // {
            //   label: "Python Driver",
            //   type: "link",
            //   href: "https://github.com/timeplus-io/proton-python-driver",
            // },
            {
              label: "Go Driver",
              type: "link",
              href: "https://github.com/timeplus-io/proton-go-driver",
            },
            {
              label: "C++ Client",
              type: "link",
              href: "https://github.com/timeplus-io/timeplus-cpp",
            },
            {
              label: "Rust Client",
              type: "link",
              href: "https://crates.io/crates/proton_client",
            },
            {
              label: "OCaml Client",
              type: "link",
              href: "https://github.com/mfreeman451/proton-ocaml-driver",
            },
            {
              label: "Timeplus REST API",
              type: "link",
              href: "https://docs.timeplus.com/rest",
            },
            "proton-ingest-api",
            {
              type: "doc",
              id: "ingest-api",
            },
            {
              type: "doc",
              id: "query-api",
            },
          ],
        },
        {
          type: "doc",
          id: "redpanda-connect",
        },
        {
          type: "category",
          label: "Third-party Tools",
          link: {
            type: "generated-index",
            title: "Third-party Tools",
            description: "Integrate Timeplus to your tool stacks.",
            slug: "/category/tools",
            keywords: ["guides"],
          },
          items: [
            {
              type: "doc",
              id: "integration-grafana",
            },
            "sling",
            "kafka-connect",
            // {
            //   label: "Push data to Timeplus via Airbyte",
            //   type: "link",
            //   href: "https://airbyte.com/connectors/timeplus",
            // },
            // {
            //   label: "Push data to Timeplus via Meltano",
            //   type: "link",
            //   href: "https://www.timeplus.com/post/meltano-timeplus-target",
            // },
            "flyway",
            // "terraform",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "DEPLOYMENT",
      items: [
        {
          type: "category",
          label: "Timeplus Enterprise Self-hosted",
          items: [
            "bare-metal-install",
            {
              type: "doc",
              id: "k8s-helm",
            },
          ],
        },
        {
          type: "doc",
          id: "byoc",
        },
        {
          type: "doc",
          id: "server_config",
        },
        "proton-ports",
        {
          type: "doc",
          id: "rbac",
        },
      ],
    },
    {
      type: "category",
      label: "TROUBLESHOOTING",
      items: [
        "troubleshooting",
        "system-stream-state-log",
        "system-stream-metric-log",
        "system-views",
        "prometheus",
      ],
    },
    {
      type: "category",
      label: "RELEASES",
      link: {
        type: "doc",
        id: "release-notes",
      },
      items: [
        "enterprise-v3.0",
        "enterprise-v2.8",
        "enterprise-v2.7",
        "enterprise-v2.6",
        "enterprise-v2.5",
        {
          type: "category",
          label: "Older 2.x Releases",
          items: ["enterprise-v2.4", "enterprise-v2.3"],
        },
        "v2-release-notes",
        "release-downloads",
        {
          type: "category",
          label: "Older Releases",
          items: [
            "v1-release-notes",
            "public-beta-2",
            "public-beta-1",
            "private-beta-2",
            "private-beta-1",
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
