files:
  - "docs/*"
dictionaries:
  - spellchecker/dic.txt
reports:
  - spellchecker/report.json
  - spellchecker/report.junit.xml
ignore:
  - key\d
  - 1f71acbf-59fc-427d-a634-1679b48029a9
  - 2a02:aa08:e000:3100
  - c\d+
  - u\d+
  - t\d+
  - \d+GB
  - \d+MB
  - array_.*
  - to_.*
  - json_extract_.*
  - exp\d+
  - log\d+
  - option\d
  - user\d
  - scalar\d
  - \d+ms
  - "[A-Z0-9]{6}"
  - b\d{5}
  - step\d
  - array\d
  - number\d
  - string\d
  - datestring\d
  - json\d
  - dateString\d
  - changelog_[_\d]+
  - v[\.\d]+
  - cloud_step\d
  - role\d
