files:
  - "docs/*"
dictionaries:
  - spellchecker/dic.txt
reports:
  - spellchecker/report.json
  - spellchecker/report.junit.xml
ignore:
  - "[A-Z0-9]{6}"
  - "\\b\\w+=\\w+\\b"
  - "\\b\\w+\\."
  - .*_logstore_.*
  - .*_port
  - .*_sn
  - 1f71acbf-59fc-427d-a634-1679b48029a9
  - 2a02:aa08:e000:3100
  - \d+GB
  - \d+Gi
  - \d+MB
  - \d+ms
  - \ds
  - array\d
  - array_.*
  - b\d{5}
  - c\d+
  - changelog_[_\d]+
  - cloud_step\d
  - datestring\d
  - dateString\d
  - exp\d+
  - ingest_.*
  - json\d
  - json_extract_.*
  - key\d
  - kvstore_.*
  - log\d+
  - logstore_.*
  - metastore_.*
  - mv\d+
  - mv_.*
  - node\d+
  - number\d
  - option\d
  - role\d
  - s3_.*
  - scalar\d
  - step\d
  - string\d
  - t\d+
  - to_.*
  - u\d+
  - user\d
  - create_dictionary_.*
  - v[\.\d]+
